import { ProductCondition } from '../../src/resources/products/entities/product-condition.entity';
import { ProductStatus } from '../../src/resources/products/entities/produc-status.entity';
import { TransactionStatus } from '../../src/resources/transactions/entities/transaction-status';

export const SEED_PASSWORD = 'Fernanpop123!';

export interface SeedUser {
  uid: string;
  email: string;
  displayName: string;
  photoURL?: string;
}

export const SEED_USERS: SeedUser[] = [
  {
    uid: 'seed-seller-maria',
    email: 'maria@fernanpop.dev',
    displayName: 'María García',
    photoURL: 'https://i.pravatar.cc/150?u=seed-seller-maria',
  },
  {
    uid: 'seed-seller-carlos',
    email: 'carlos@fernanpop.dev',
    displayName: 'Carlos López',
    photoURL: 'https://i.pravatar.cc/150?u=seed-seller-carlos',
  },
  {
    uid: 'seed-buyer-ana',
    email: 'ana@fernanpop.dev',
    displayName: 'Ana Martínez',
    photoURL: 'https://i.pravatar.cc/150?u=seed-buyer-ana',
  },
  {
    uid: 'seed-buyer-pedro',
    email: 'pedro@fernanpop.dev',
    displayName: 'Pedro Ruiz',
    photoURL: 'https://i.pravatar.cc/150?u=seed-buyer-pedro',
  },
];

export type SeedProductStatus = ProductStatus[] | 'available';

export interface SeedProduct {
  key: string;
  sellerUid: string;
  title: string;
  desc: string;
  price: number;
  categoryId: string;
  condition: ProductCondition;
  imageUrl: string;
  status: SeedProductStatus;
  daysAgo: number;
}

export interface SeedTransaction {
  key: string;
  productKey: string;
  buyerUid: string;
  status: TransactionStatus;
  daysAgo: number;
}

export interface SeedFavorite {
  userUid: string;
  productKey: string;
  daysAgo: number;
}

export interface SeedReview {
  transactionKey: string;
  score: number;
  description: string;
}

export const SEED_PRODUCTS: SeedProduct[] = [
  {
    key: 'camiseta-nike',
    sellerUid: 'seed-seller-maria',
    title: 'Camiseta Nike vintage',
    desc: 'Camiseta Nike talla M, estampado retro. Muy buen estado general.',
    price: 18,
    categoryId: 'ropa',
    condition: ProductCondition.GOOD,
    imageUrl: 'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?auto=format&fit=crop&w=800&h=600&q=80',
    status: 'available',
    daysAgo: 6,
  },
  {
    key: 'auriculares-bluetooth',
    sellerUid: 'seed-seller-maria',
    title: 'Auriculares Bluetooth',
    desc: 'Auriculares inalámbricos con cancelación de ruido. Incluyen funda.',
    price: 45,
    categoryId: 'electronica',
    condition: ProductCondition.LIKE_NEW,
    imageUrl: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&h=600&q=80',
    status: 'available',
    daysAgo: 5,
  },
  {
    key: 'lampara-mesa',
    sellerUid: 'seed-seller-maria',
    title: 'Lámpara de mesa',
    desc: 'Lámpara nórdica de madera y lino. Perfecta para salón o dormitorio.',
    price: 32,
    categoryId: 'hogar',
    condition: ProductCondition.GOOD,
    imageUrl: 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=800&h=600&q=80',
    status: [ProductStatus.RESERVED],
    daysAgo: 4,
  },
  {
    key: 'balon-futbol',
    sellerUid: 'seed-seller-maria',
    title: 'Balón de fútbol',
    desc: 'Balón oficial talla 5. Usado en partidos amateur.',
    price: 22,
    categoryId: 'deportes',
    condition: ProductCondition.WORN,
    imageUrl: 'https://images.unsplash.com/photo-1574629810360-7efbbe195018?auto=format&fit=crop&w=800&h=600&q=80',
    status: [ProductStatus.SOLD],
    daysAgo: 3,
  },
  {
    key: 'chaqueta-invierno',
    sellerUid: 'seed-seller-carlos',
    title: 'Chaqueta de invierno',
    desc: 'Chaqueta acolchada talla L, color negro. Abriga mucho.',
    price: 55,
    categoryId: 'ropa',
    condition: ProductCondition.NEW,
    imageUrl: 'https://images.unsplash.com/photo-1544022613-e87ca75a784a?auto=format&fit=crop&w=800&h=600&q=80',
    status: 'available',
    daysAgo: 6,
  },
  {
    key: 'tablet-samsung',
    sellerUid: 'seed-seller-carlos',
    title: 'Tablet Samsung',
    desc: 'Tablet 10 pulgadas con funda y cargador original.',
    price: 120,
    categoryId: 'electronica',
    condition: ProductCondition.GOOD,
    imageUrl: 'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?auto=format&fit=crop&w=800&h=600&q=80',
    status: 'available',
    daysAgo: 5,
  },
  {
    key: 'set-sartenes',
    sellerUid: 'seed-seller-carlos',
    title: 'Set de sartenes',
    desc: 'Juego de 3 sartenes antiadherentes. Apenas usadas.',
    price: 38,
    categoryId: 'hogar',
    condition: ProductCondition.LIKE_NEW,
    imageUrl: 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&w=800&h=600&q=80',
    status: 'available',
    daysAgo: 4,
  },
  {
    key: 'raqueta-tenis',
    sellerUid: 'seed-seller-carlos',
    title: 'Raqueta de tenis',
    desc: 'Raqueta Wilson con grip nuevo. Ideal para principiantes.',
    price: 65,
    categoryId: 'deportes',
    condition: ProductCondition.GOOD,
    imageUrl: 'https://images.unsplash.com/photo-1626224583764-f87db24ac4ea?auto=format&fit=crop&w=800&h=600&q=80',
    status: 'available',
    daysAgo: 2,
  },
  {
    key: 'zapatillas-running',
    sellerUid: 'seed-seller-maria',
    title: 'Zapatillas running',
    desc: 'Zapatillas de running talla 42, amortiguación excelente. Poco uso.',
    price: 75,
    categoryId: 'deportes',
    condition: ProductCondition.LIKE_NEW,
    imageUrl: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&h=600&q=80',
    status: 'available',
    daysAgo: 14,
  },
  {
    key: 'jersey-ciclismo',
    sellerUid: 'seed-seller-maria',
    title: 'Jersey de ciclismo',
    desc: 'Maillot de ciclismo talla M, tejido transpirable. Ideal para ruta.',
    price: 28,
    categoryId: 'ropa',
    condition: ProductCondition.GOOD,
    imageUrl: 'https://images.unsplash.com/photo-1618354691373-d851c5c3a990?auto=format&fit=crop&w=800&h=600&q=80',
    status: 'available',
    daysAgo: 13,
  },
  {
    key: 'pantalon-vaquero',
    sellerUid: 'seed-seller-maria',
    title: 'Pantalón vaquero',
    desc: 'Vaquero slim fit talla 32, denim oscuro. Muy versátil.',
    price: 35,
    categoryId: 'ropa',
    condition: ProductCondition.GOOD,
    imageUrl: 'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?auto=format&fit=crop&w=800&h=600&q=80',
    status: 'available',
    daysAgo: 12,
  },
  {
    key: 'vestido-verano',
    sellerUid: 'seed-seller-carlos',
    title: 'Vestido de verano',
    desc: 'Vestido ligero talla S, estampado floral. Perfecto para temporada cálida.',
    price: 42,
    categoryId: 'ropa',
    condition: ProductCondition.LIKE_NEW,
    imageUrl: 'https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?auto=format&fit=crop&w=800&h=600&q=80',
    status: 'available',
    daysAgo: 11,
  },
  {
    key: 'smartwatch',
    sellerUid: 'seed-seller-carlos',
    title: 'Smartwatch',
    desc: 'Reloj inteligente con monitor de actividad y notificaciones.',
    price: 89,
    categoryId: 'electronica',
    condition: ProductCondition.LIKE_NEW,
    imageUrl: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=800&h=600&q=80',
    status: 'available',
    daysAgo: 10,
  },
  {
    key: 'teclado-mecanico',
    sellerUid: 'seed-seller-maria',
    title: 'Teclado mecánico',
    desc: 'Teclado mecánico RGB, switches táctiles. Incluye reposamuñecas.',
    price: 95,
    categoryId: 'electronica',
    condition: ProductCondition.NEW,
    imageUrl: 'https://images.unsplash.com/photo-1618384887929-16ec33fab9ef?auto=format&fit=crop&w=800&h=600&q=80',
    status: 'available',
    daysAgo: 9,
  },
  {
    key: 'monitor-24',
    sellerUid: 'seed-seller-carlos',
    title: 'Monitor 24 pulgadas',
    desc: 'Monitor Full HD 24", panel IPS. Sin marcas en pantalla.',
    price: 140,
    categoryId: 'electronica',
    condition: ProductCondition.GOOD,
    imageUrl: 'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?auto=format&fit=crop&w=800&h=600&q=80',
    status: 'available',
    daysAgo: 8,
  },
  {
    key: 'camara-reflex',
    sellerUid: 'seed-seller-maria',
    title: 'Cámara réflex',
    desc: 'Cámara réflex con objetivo 18-55mm. Funciona perfectamente.',
    price: 280,
    categoryId: 'electronica',
    condition: ProductCondition.GOOD,
    imageUrl: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&w=800&h=600&q=80',
    status: 'available',
    daysAgo: 7,
  },
  {
    key: 'altavoz-portatil',
    sellerUid: 'seed-seller-carlos',
    title: 'Altavoz portátil',
    desc: 'Altavoz Bluetooth resistente al agua. Gran autonomía de batería.',
    price: 58,
    categoryId: 'electronica',
    condition: ProductCondition.LIKE_NEW,
    imageUrl: 'https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&h=600&q=80',
    status: 'available',
    daysAgo: 6,
  },
  {
    key: 'sofa-tapizado',
    sellerUid: 'seed-seller-maria',
    title: 'Sofá tapizado',
    desc: 'Sofá de dos plazas, tapizado gris. Muy cómodo y limpio.',
    price: 350,
    categoryId: 'hogar',
    condition: ProductCondition.GOOD,
    imageUrl: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=800&h=600&q=80',
    status: 'available',
    daysAgo: 14,
  },
  {
    key: 'alfombra-sala',
    sellerUid: 'seed-seller-carlos',
    title: 'Alfombra de sala',
    desc: 'Alfombra de pelo corto 160x230 cm. Tonos neutros.',
    price: 75,
    categoryId: 'hogar',
    condition: ProductCondition.GOOD,
    imageUrl: 'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=800&h=600&q=80',
    status: 'available',
    daysAgo: 13,
  },
  {
    key: 'microondas',
    sellerUid: 'seed-seller-maria',
    title: 'Microondas',
    desc: 'Microondas 20L con grill. Funciona sin problemas.',
    price: 55,
    categoryId: 'hogar',
    condition: ProductCondition.LIKE_NEW,
    imageUrl: 'https://images.unsplash.com/photo-1593618998160-e34014e67546?auto=format&fit=crop&w=800&h=600&q=80',
    status: 'available',
    daysAgo: 12,
  },
  {
    key: 'juego-vasos',
    sellerUid: 'seed-seller-carlos',
    title: 'Juego de vasos',
    desc: 'Set de 6 vasos de cristal templado. Sin roturas.',
    price: 18,
    categoryId: 'hogar',
    condition: ProductCondition.NEW,
    imageUrl: 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?auto=format&fit=crop&w=800&h=600&q=80',
    status: 'available',
    daysAgo: 11,
  },
  {
    key: 'cafetera',
    sellerUid: 'seed-seller-maria',
    title: 'Cafetera italiana',
    desc: 'Cafetera moka de acero para 6 tazas. Como nueva.',
    price: 48,
    categoryId: 'hogar',
    condition: ProductCondition.GOOD,
    imageUrl: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=800&h=600&q=80',
    status: 'available',
    daysAgo: 10,
  },
  {
    key: 'bicicleta-urbana',
    sellerUid: 'seed-seller-carlos',
    title: 'Bicicleta urbana',
    desc: 'Bici de paseo con cambio de marchas. Revisada recientemente.',
    price: 220,
    categoryId: 'deportes',
    condition: ProductCondition.GOOD,
    imageUrl: 'https://images.unsplash.com/photo-1571068316344-75bc76f77890?auto=format&fit=crop&w=800&h=600&q=80',
    status: 'available',
    daysAgo: 9,
  },
  {
    key: 'pesas-ajustables',
    sellerUid: 'seed-seller-maria',
    title: 'Pesas ajustables',
    desc: 'Par de mancuernas ajustables de 2 a 24 kg. Para entrenar en casa.',
    price: 85,
    categoryId: 'deportes',
    condition: ProductCondition.LIKE_NEW,
    imageUrl: 'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?auto=format&fit=crop&w=800&h=600&q=80',
    status: 'available',
    daysAgo: 8,
  },
  {
    key: 'mochila-senderismo',
    sellerUid: 'seed-seller-carlos',
    title: 'Mochila de senderismo',
    desc: 'Mochila 40L con soporte lumbar y funda para lluvia.',
    price: 40,
    categoryId: 'deportes',
    condition: ProductCondition.GOOD,
    imageUrl: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=800&h=600&q=80',
    status: 'available',
    daysAgo: 7,
  },
  {
    key: 'libros-coleccion',
    sellerUid: 'seed-seller-maria',
    title: 'Colección de libros',
    desc: 'Lote de 5 novelas de ficción contemporánea. Buen estado.',
    price: 25,
    categoryId: 'otros',
    condition: ProductCondition.GOOD,
    imageUrl: 'https://images.unsplash.com/photo-1495446815901-a7297e633e8d?auto=format&fit=crop&w=800&h=600&q=80',
    status: 'available',
    daysAgo: 6,
  },
  {
    key: 'reloj-pared',
    sellerUid: 'seed-seller-carlos',
    title: 'Reloj de pared',
    desc: 'Reloj de pared minimalista, mecanismo silencioso.',
    price: 30,
    categoryId: 'hogar',
    condition: ProductCondition.LIKE_NEW,
    imageUrl: 'https://images.unsplash.com/photo-1563861826100-9cb868fdbe1c?auto=format&fit=crop&w=800&h=600&q=80',
    status: 'available',
    daysAgo: 5,
  },
  {
    key: 'drone',
    sellerUid: 'seed-seller-maria',
    title: 'Drone con cámara',
    desc: 'Drone plegable con cámara HD. Incluye batería extra.',
    price: 310,
    categoryId: 'electronica',
    condition: ProductCondition.LIKE_NEW,
    imageUrl: 'https://images.unsplash.com/photo-1473968512647-3e447244af8f?auto=format&fit=crop&w=800&h=600&q=80',
    status: 'available',
    daysAgo: 4,
  },
  {
    key: 'guitarra-acustica',
    sellerUid: 'seed-seller-carlos',
    title: 'Guitarra acústica',
    desc: 'Guitarra acústica de tamaño completo. Afinada y lista para tocar.',
    price: 190,
    categoryId: 'otros',
    condition: ProductCondition.GOOD,
    imageUrl: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?auto=format&fit=crop&w=800&h=600&q=80',
    status: 'available',
    daysAgo: 3,
  },
  {
    key: 'sudadera',
    sellerUid: 'seed-seller-maria',
    title: 'Sudadera con capucha',
    desc: 'Sudadera oversize talla L, algodón grueso. Muy cómoda.',
    price: 32,
    categoryId: 'ropa',
    condition: ProductCondition.NEW,
    imageUrl: 'https://images.unsplash.com/photo-1556821840-3a63f95609a7?auto=format&fit=crop&w=800&h=600&q=80',
    status: 'available',
    daysAgo: 2,
  },
  {
    key: 'botas-trekking',
    sellerUid: 'seed-seller-carlos',
    title: 'Botas de trekking',
    desc: 'Botas impermeables talla 41. Ideales para montaña y senderismo.',
    price: 70,
    categoryId: 'deportes',
    condition: ProductCondition.GOOD,
    imageUrl: 'https://images.unsplash.com/photo-1605812860427-4024433a70fd?auto=format&fit=crop&w=800&h=600&q=80',
    status: 'available',
    daysAgo: 54,
  },
  {
    key: 'raton-gaming',
    sellerUid: 'seed-seller-maria',
    title: 'Ratón gaming',
    desc: 'Ratón ergonómico con RGB y 6 botones programables.',
    price: 25,
    categoryId: 'electronica',
    condition: ProductCondition.LIKE_NEW,
    imageUrl: 'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?auto=format&fit=crop&w=800&h=600&q=80',
    status: 'available',
    daysAgo: 53,
  },
  {
    key: 'consola-retro',
    sellerUid: 'seed-seller-carlos',
    title: 'Consola retro',
    desc: 'Consola de videojuegos con dos mandos. Funciona perfectamente.',
    price: 180,
    categoryId: 'electronica',
    condition: ProductCondition.GOOD,
    imageUrl: 'https://images.unsplash.com/photo-1606813907291-d86efa9b94db?auto=format&fit=crop&w=800&h=600&q=80',
    status: 'available',
    daysAgo: 52,
  },
  {
    key: 'maleta-viaje',
    sellerUid: 'seed-seller-maria',
    title: 'Maleta de viaje',
    desc: 'Maleta rígida mediana con ruedas 360°. Muy resistente.',
    price: 50,
    categoryId: 'otros',
    condition: ProductCondition.GOOD,
    imageUrl: 'https://images.unsplash.com/photo-1566576912321-d58ddd7a6088?auto=format&fit=crop&w=800&h=600&q=80',
    status: 'available',
    daysAgo: 51,
  },
  {
    key: 'pelota-baloncesto',
    sellerUid: 'seed-seller-carlos',
    title: 'Pelota de baloncesto',
    desc: 'Balón oficial talla 7. Buen agarre y rebote.',
    price: 15,
    categoryId: 'deportes',
    condition: ProductCondition.WORN,
    imageUrl: 'https://images.unsplash.com/photo-1546519638-68e109498ffc?auto=format&fit=crop&w=800&h=600&q=80',
    status: 'available',
    daysAgo: 50,
  },
  {
    key: 'patines-linea',
    sellerUid: 'seed-seller-maria',
    title: 'Patines en línea',
    desc: 'Patines talla 40 con freno trasero. Casi sin uso.',
    price: 60,
    categoryId: 'deportes',
    condition: ProductCondition.LIKE_NEW,
    imageUrl: 'https://images.unsplash.com/photo-1566150905458-1bf1fc113f0d?auto=format&fit=crop&w=800&h=600&q=80',
    status: 'available',
    daysAgo: 49,
  },
  {
    key: 'toalla-playa',
    sellerUid: 'seed-seller-carlos',
    title: 'Toalla de playa',
    desc: 'Toalla grande de algodón, secado rápido. Estampado veraniego.',
    price: 12,
    categoryId: 'hogar',
    condition: ProductCondition.GOOD,
    imageUrl: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?auto=format&fit=crop&w=800&h=600&q=80',
    status: 'available',
    daysAgo: 48,
  },
  {
    key: 'bateria-externa',
    sellerUid: 'seed-seller-maria',
    title: 'Batería externa',
    desc: 'Power bank 20000 mAh con carga rápida USB-C.',
    price: 22,
    categoryId: 'electronica',
    condition: ProductCondition.NEW,
    imageUrl: 'https://images.unsplash.com/photo-1612198188060-c7c2a3b66eae?auto=format&fit=crop&w=800&h=600&q=80',
    status: 'available',
    daysAgo: 47,
  },
  {
    key: 'casco-bici',
    sellerUid: 'seed-seller-carlos',
    title: 'Casco de ciclismo',
    desc: 'Casco ligero con ventilación. Talla M, color blanco.',
    price: 45,
    categoryId: 'deportes',
    condition: ProductCondition.LIKE_NEW,
    imageUrl: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?auto=format&fit=crop&w=800&h=600&q=80',
    status: 'available',
    daysAgo: 46,
  },
  {
    key: 'macetas-plantas',
    sellerUid: 'seed-seller-maria',
    title: 'Macetas con plantas',
    desc: 'Set de 3 macetas con plantas de interior. Fácil mantenimiento.',
    price: 15,
    categoryId: 'hogar',
    condition: ProductCondition.NEW,
    imageUrl: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?auto=format&fit=crop&w=800&h=600&q=80',
    status: 'available',
    daysAgo: 45,
  },
  {
    key: 'espejo-decorativo',
    sellerUid: 'seed-seller-carlos',
    title: 'Espejo decorativo',
    desc: 'Espejo redondo con marco dorado. Diámetro 60 cm.',
    price: 28,
    categoryId: 'hogar',
    condition: ProductCondition.GOOD,
    imageUrl: 'https://images.unsplash.com/photo-1618220179428-22790b461013?auto=format&fit=crop&w=800&h=600&q=80',
    status: 'available',
    daysAgo: 44,
  },
  {
    key: 'bolso-cuero',
    sellerUid: 'seed-seller-maria',
    title: 'Bolso de cuero',
    desc: 'Bolso bandolera de cuero genuino. Varios compartimentos.',
    price: 48,
    categoryId: 'ropa',
    condition: ProductCondition.GOOD,
    imageUrl: 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?auto=format&fit=crop&w=800&h=600&q=80',
    status: 'available',
    daysAgo: 43,
  },
  {
    key: 'gafas-de-sol',
    sellerUid: 'seed-seller-carlos',
    title: 'Gafas de sol',
    desc: 'Gafas polarizadas estilo aviador. Incluyen estuche.',
    price: 35,
    categoryId: 'otros',
    condition: ProductCondition.LIKE_NEW,
    imageUrl: 'https://images.unsplash.com/photo-1577803645773-f96470509666?auto=format&fit=crop&w=800&h=600&q=80',
    status: 'available',
    daysAgo: 42,
  },
  {
    key: 'bufanda-invierno',
    sellerUid: 'seed-seller-maria',
    title: 'Bufanda de invierno',
    desc: 'Bufanda de lana merino, suave y abrigada. Color gris.',
    price: 14,
    categoryId: 'ropa',
    condition: ProductCondition.NEW,
    imageUrl: 'https://images.unsplash.com/photo-1601924994987-69e26d50dc26?auto=format&fit=crop&w=800&h=600&q=80',
    status: 'available',
    daysAgo: 41,
  },
  {
    key: 'escritorio-madera',
    sellerUid: 'seed-seller-carlos',
    title: 'Escritorio de madera',
    desc: 'Escritorio 120x60 cm con cajón. Ideal para teletrabajo.',
    price: 95,
    categoryId: 'hogar',
    condition: ProductCondition.GOOD,
    imageUrl: 'https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?auto=format&fit=crop&w=800&h=600&q=80',
    status: 'available',
    daysAgo: 40,
  },
  {
    key: 'barbacoa-carbon',
    sellerUid: 'seed-seller-maria',
    title: 'Barbacoa de carbón',
    desc: 'Barbacoa portátil de acero. Perfecta para terraza o jardín.',
    price: 80,
    categoryId: 'hogar',
    condition: ProductCondition.GOOD,
    imageUrl: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&w=800&h=600&q=80',
    status: 'available',
    daysAgo: 39,
  },
  {
    key: 'aspiradora-robot',
    sellerUid: 'seed-seller-carlos',
    title: 'Aspiradora robot',
    desc: 'Robot aspirador con mapeo y app móvil. Autonomía 90 min.',
    price: 160,
    categoryId: 'hogar',
    condition: ProductCondition.LIKE_NEW,
    imageUrl: 'https://images.unsplash.com/photo-1527515637462-cff94eecc1ac?auto=format&fit=crop&w=800&h=600&q=80',
    status: 'available',
    daysAgo: 38,
  },
  {
    key: 'esterilla-yoga',
    sellerUid: 'seed-seller-maria',
    title: 'Esterilla de yoga',
    desc: 'Esterilla antideslizante 6 mm. Incluye correa de transporte.',
    price: 20,
    categoryId: 'deportes',
    condition: ProductCondition.NEW,
    imageUrl: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?auto=format&fit=crop&w=800&h=600&q=80',
    status: 'available',
    daysAgo: 37,
  },
  {
    key: 'webcam-hd',
    sellerUid: 'seed-seller-carlos',
    title: 'Webcam HD',
    desc: 'Webcam 1080p con micrófono integrado. Clip para monitor.',
    price: 38,
    categoryId: 'electronica',
    condition: ProductCondition.GOOD,
    imageUrl: 'https://images.unsplash.com/photo-1588196749597-9ff075ee6b5b?auto=format&fit=crop&w=800&h=600&q=80',
    status: 'available',
    daysAgo: 36,
  },
  {
    key: 'gorra-snapback',
    sellerUid: 'seed-seller-maria',
    title: 'Gorra snapback',
    desc: 'Gorra ajustable estilo urbano. Logo bordado.',
    price: 16,
    categoryId: 'ropa',
    condition: ProductCondition.NEW,
    imageUrl: 'https://images.unsplash.com/photo-1588850561407-ed78c282e89b?auto=format&fit=crop&w=800&h=600&q=80',
    status: 'available',
    daysAgo: 35,
  },
  {
    key: 'iphone-usado',
    sellerUid: 'seed-seller-carlos',
    title: 'iPhone de segunda mano',
    desc: 'iPhone en buen estado, batería al 85%. Sin arañazos en pantalla.',
    price: 350,
    categoryId: 'electronica',
    condition: ProductCondition.GOOD,
    imageUrl: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=800&h=600&q=80',
    status: 'available',
    daysAgo: 34,
  },
  {
    key: 'portatil-hp',
    sellerUid: 'seed-seller-maria',
    title: 'Portátil HP',
    desc: 'Portátil 15" con 16 GB RAM y SSD 512 GB. Ideal para estudio.',
    price: 420,
    categoryId: 'electronica',
    condition: ProductCondition.GOOD,
    imageUrl: 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=800&h=600&q=80',
    status: 'available',
    daysAgo: 33,
  },
  {
    key: 'router-mesh',
    sellerUid: 'seed-seller-carlos',
    title: 'Router WiFi mesh',
    desc: 'Sistema mesh de dos nodos. Cobertura completa en casa.',
    price: 65,
    categoryId: 'electronica',
    condition: ProductCondition.LIKE_NEW,
    imageUrl: 'https://images.unsplash.com/photo-1544197150-b99a580bb7a8?auto=format&fit=crop&w=800&h=600&q=80',
    status: 'available',
    daysAgo: 32,
  },
  {
    key: 'disco-ssd',
    sellerUid: 'seed-seller-maria',
    title: 'Disco SSD externo',
    desc: 'SSD portátil 1 TB USB 3.2. Velocidad de lectura 1050 MB/s.',
    price: 55,
    categoryId: 'electronica',
    condition: ProductCondition.NEW,
    imageUrl: 'https://images.unsplash.com/photo-1597872200969-2b65d56bd16b?auto=format&fit=crop&w=800&h=600&q=80',
    status: 'available',
    daysAgo: 31,
  },
  {
    key: 'polo-verano',
    sellerUid: 'seed-seller-carlos',
    title: 'Polo de verano',
    desc: 'Polo de algodón talla M, color azul marino. Muy fresco.',
    price: 22,
    categoryId: 'ropa',
    condition: ProductCondition.NEW,
    imageUrl: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=800&h=600&q=80',
    status: 'available',
    daysAgo: 30,
  },
  {
    key: 'falda-midi',
    sellerUid: 'seed-seller-maria',
    title: 'Falda midi',
    desc: 'Falda plisada talla S. Tejido ligero y elegante.',
    price: 36,
    categoryId: 'ropa',
    condition: ProductCondition.LIKE_NEW,
    imageUrl: 'https://images.unsplash.com/photo-1595777457583-95e059d581b8?auto=format&fit=crop&w=800&h=600&q=80',
    status: 'available',
    daysAgo: 29,
  },
  {
    key: 'sandalias-playa',
    sellerUid: 'seed-seller-carlos',
    title: 'Sandalias de playa',
    desc: 'Sandalias cómodas talla 39. Suela antideslizante.',
    price: 24,
    categoryId: 'ropa',
    condition: ProductCondition.GOOD,
    imageUrl: 'https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?auto=format&fit=crop&w=800&h=600&q=80',
    status: 'available',
    daysAgo: 28,
  },
  {
    key: 'silla-escritorio',
    sellerUid: 'seed-seller-maria',
    title: 'Silla de escritorio',
    desc: 'Silla ergonómica con reposabrazos y soporte lumbar.',
    price: 110,
    categoryId: 'hogar',
    condition: ProductCondition.GOOD,
    imageUrl: 'https://images.unsplash.com/photo-1506439773649-6e0eb8cfb237?auto=format&fit=crop&w=800&h=600&q=80',
    status: 'available',
    daysAgo: 27,
  },
  {
    key: 'cuadro-abstracto',
    sellerUid: 'seed-seller-carlos',
    title: 'Cuadro abstracto',
    desc: 'Lienzo 50x70 cm con marco de madera. Arte moderno.',
    price: 45,
    categoryId: 'hogar',
    condition: ProductCondition.LIKE_NEW,
    imageUrl: 'https://images.unsplash.com/photo-1578301978018-3005759f48f7?auto=format&fit=crop&w=800&h=600&q=80',
    status: 'available',
    daysAgo: 26,
  },
  {
    key: 'cortinas-lino',
    sellerUid: 'seed-seller-maria',
    title: 'Cortinas de lino',
    desc: 'Par de cortinas beige 140x260 cm. Filtran la luz suavemente.',
    price: 42,
    categoryId: 'hogar',
    condition: ProductCondition.GOOD,
    imageUrl: 'https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?auto=format&fit=crop&w=800&h=600&q=80',
    status: 'available',
    daysAgo: 25,
  },
  {
    key: 'licuadora-pro',
    sellerUid: 'seed-seller-carlos',
    title: 'Licuadora profesional',
    desc: 'Licuadora de alta potencia con jarra de vidrio 1.5 L.',
    price: 72,
    categoryId: 'hogar',
    condition: ProductCondition.LIKE_NEW,
    imageUrl: 'https://images.unsplash.com/photo-1585515320310-259814833e62?auto=format&fit=crop&w=800&h=600&q=80',
    status: 'available',
    daysAgo: 24,
  },
  {
    key: 'monopatin',
    sellerUid: 'seed-seller-maria',
    title: 'Monopatín',
    desc: 'Skateboard completo con ruedas nuevas. Listo para patinar.',
    price: 55,
    categoryId: 'deportes',
    condition: ProductCondition.GOOD,
    imageUrl: 'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&w=800&h=600&q=80',
    status: 'available',
    daysAgo: 23,
  },
  {
    key: 'tienda-camping',
    sellerUid: 'seed-seller-carlos',
    title: 'Tienda de camping',
    desc: 'Tienda iglú para 2 personas. Montaje rápido, impermeable.',
    price: 85,
    categoryId: 'deportes',
    condition: ProductCondition.GOOD,
    imageUrl: 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=800&h=600&q=80',
    status: 'available',
    daysAgo: 22,
  },
  {
    key: 'vinilo-clasico',
    sellerUid: 'seed-seller-maria',
    title: 'Vinilo clásico',
    desc: 'Disco de vinilo en excelente estado. Incluye funda interior.',
    price: 30,
    categoryId: 'otros',
    condition: ProductCondition.GOOD,
    imageUrl: 'https://images.unsplash.com/photo-1619983081563-430f63602796?auto=format&fit=crop&w=800&h=600&q=80',
    status: 'available',
    daysAgo: 21,
  },
  {
    key: 'perfume-dior',
    sellerUid: 'seed-seller-carlos',
    title: 'Perfume Dior',
    desc: 'Frasco con un 60% restante. Aroma fresco y duradero.',
    price: 48,
    categoryId: 'otros',
    condition: ProductCondition.LIKE_NEW,
    imageUrl: 'https://images.unsplash.com/photo-1541643600914-78b084683601?auto=format&fit=crop&w=800&h=600&q=80',
    status: 'available',
    daysAgo: 20,
  },
  {
    key: 'anillo-plata',
    sellerUid: 'seed-seller-maria',
    title: 'Anillo de plata',
    desc: 'Anillo de plata 925 con diseño minimalista. Talla 16.',
    price: 55,
    categoryId: 'otros',
    condition: ProductCondition.NEW,
    imageUrl: 'https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&w=800&h=600&q=80',
    status: 'available',
    daysAgo: 19,
  },
  {
    key: 'peluche-osito',
    sellerUid: 'seed-seller-carlos',
    title: 'Peluche osito',
    desc: 'Osito de peluche grande, lavable. Ideal para regalo.',
    price: 12,
    categoryId: 'otros',
    condition: ProductCondition.NEW,
    imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=800&h=600&q=80',
    status: 'available',
    daysAgo: 18,
  },
  {
    key: 'guantes-fitness',
    sellerUid: 'seed-seller-maria',
    title: 'Guantes de fitness',
    desc: 'Guantes para gimnasio con agarre reforzado. Talla M.',
    price: 18,
    categoryId: 'deportes',
    condition: ProductCondition.NEW,
    imageUrl: 'https://images.unsplash.com/photo-1594381898411-846e7d193883?auto=format&fit=crop&w=800&h=600&q=80',
    status: 'available',
    daysAgo: 17,
  },
  {
    key: 'chaqueton-nieve',
    sellerUid: 'seed-seller-carlos',
    title: 'Chaquetón de nieve',
    desc: 'Chaqueta técnica impermeable talla XL. Para esquí o snowboard.',
    price: 95,
    categoryId: 'ropa',
    condition: ProductCondition.GOOD,
    imageUrl: 'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?auto=format&fit=crop&w=800&h=600&q=80',
    status: 'available',
    daysAgo: 16,
  },
  {
    key: 'plancha-vapor',
    sellerUid: 'seed-seller-maria',
    title: 'Plancha de vapor',
    desc: 'Plancha con suela cerámica y disparo de vapor. Como nueva.',
    price: 40,
    categoryId: 'hogar',
    condition: ProductCondition.LIKE_NEW,
    imageUrl: 'https://images.unsplash.com/photo-1626806787461-102c1bfaaea1?auto=format&fit=crop&w=800&h=600&q=80',
    status: 'available',
    daysAgo: 15,
  },
];

export const SEED_TRANSACTIONS: SeedTransaction[] = [
  {
    key: 'tx-lampara',
    productKey: 'lampara-mesa',
    buyerUid: 'seed-buyer-ana',
    status: TransactionStatus.IN_PROCESS,
    daysAgo: 2,
  },
  {
    key: 'tx-balon',
    productKey: 'balon-futbol',
    buyerUid: 'seed-buyer-pedro',
    status: TransactionStatus.RECEIVED,
    daysAgo: 1,
  },
  {
    key: 'tx-sartenes',
    productKey: 'set-sartenes',
    buyerUid: 'seed-buyer-ana',
    status: TransactionStatus.CANCELED,
    daysAgo: 3,
  },
];

export const SEED_FAVORITES: SeedFavorite[] = [
  { userUid: 'seed-buyer-ana', productKey: 'chaqueta-invierno', daysAgo: 1 },
  { userUid: 'seed-buyer-ana', productKey: 'tablet-samsung', daysAgo: 1 },
  { userUid: 'seed-buyer-ana', productKey: 'drone', daysAgo: 2 },
  { userUid: 'seed-buyer-ana', productKey: 'portatil-hp', daysAgo: 2 },
  { userUid: 'seed-buyer-ana', productKey: 'vinilo-clasico', daysAgo: 3 },
  { userUid: 'seed-buyer-pedro', productKey: 'camiseta-nike', daysAgo: 2 },
  { userUid: 'seed-buyer-pedro', productKey: 'zapatillas-running', daysAgo: 3 },
  { userUid: 'seed-buyer-pedro', productKey: 'bicicleta-urbana', daysAgo: 1 },
  { userUid: 'seed-buyer-pedro', productKey: 'iphone-usado', daysAgo: 1 },
  { userUid: 'seed-buyer-pedro', productKey: 'consola-retro', daysAgo: 2 },
];

export const SEED_REVIEWS: SeedReview[] = [
  {
    transactionKey: 'tx-balon',
    score: 5,
    description: 'Excelente vendedor, el balón llegó en perfecto estado.',
  },
];

export function daysAgoToDate(daysAgo: number): Date {
  const date = new Date();
  date.setDate(date.getDate() - daysAgo);
  date.setHours(12, 0, 0, 0);
  return date;
}
